trigger: none
pr: none

# Manual trigger with parameters
parameters:
- name: environment
  displayName: "Select environment"
  type: string
  default: "dev"
  values:
  - dev
  - test
  - prod

stages:
- stage: Deploy
  jobs:
  - job: DeployJob
    steps:
    - script: echo "Deploying to ${{ parameters.environment }}"
