trigger:
- none

pool:
  name: SelfHostedAzureUbuntuVM

variables:
  IMAGE_NAME: my-demo-app
  IMAGE_TAG: latest

steps:
  # Step 1: Clean up old Docker images
  - script: |
      echo "Cleaning up old Docker images..."
      docker rmi -f $(docker images -q) || echo "No images to delete"
    displayName: "Clean up existing Docker images"

  # Step 2: Build the Docker image
  - script: |
      echo "Building Docker image..."
      docker build -t $(IMAGE_NAME):$(IMAGE_TAG) .
    displayName: "Build Docker image"

  # Step 3: Run the container using the entrypoint
  - script: |
      echo "Running Docker container..."
      docker run --rm \
        --name $(IMAGE_NAME)-container \
        $(IMAGE_NAME):$(IMAGE_TAG)
    displayName: "Run Docker container"
