trigger: none

stages:
- stage: RetriveKeyVaultInfo
  displayName: 'Retrieve Key vault info'
  jobs:
  - job: FetchKV
    displayName: 'Fetch hub-rg key valult Info'
    pool:
      name: SelfHostedAzureUbuntuVM   # Your self-hosted agent pool
    steps:
    - task: AzureKeyVault@2
      displayName: 'Get Key Vault Info'
      inputs:
        azureSubscription: 'KeyVaultServiceConnectionVishnu1'   # Service connection name
        KeyVaultName: 'hub-keyvault-104'  
        SecretsFilter: '*'
        